spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
        show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false

server:
  port: 8080
  servlet:
    context-path: /api/v1/make-couples